function HomePage() {
    return (
        <div className="page-wrapper">
            <h1>Dit is een test header</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur atque commodi cupiditate delectus dignissimos dolorem enim error est et ex, excepturi harum hic id illo iure maxime minima minus natus obcaecati odio officiis quae quam quas quasi qui ratione repellendus similique vero voluptatem voluptates. Ab at beatae commodi cumque earum eligendi enim exercitationem explicabo facilis incidunt itaque labore laboriosam minima mollitia nemo, nostrum odio possimus quaerat quibusdam quod recusandae reprehenderit, sint tenetur totam ullam vero voluptatem voluptatum. Corporis cumque doloribus ducimus error excepturi placeat repellendus sunt. Accusamus consequatur doloribus dolorum ducimus neque optio vel? Commodi minima molestiae placeat quasi rerum?</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur atque commodi cupiditate delectus dignissimos dolorem enim error est et ex, excepturi harum hic id illo iure maxime minima minus natus obcaecati odio officiis quae quam quas quasi qui ratione repellendus similique vero voluptatem voluptates. Ab at beatae commodi cumque earum eligendi enim exercitationem explicabo facilis incidunt itaque labore laboriosam minima mollitia nemo, nostrum odio possimus quaerat quibusdam quod recusandae reprehenderit, sint tenetur totam ullam vero voluptatem voluptatum. Corporis cumque doloribus ducimus error excepturi placeat repellendus sunt. Accusamus consequatur doloribus dolorum ducimus neque optio vel? Commodi minima molestiae placeat quasi rerum?</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur atque commodi cupiditate delectus dignissimos dolorem enim error est et ex, excepturi harum hic id illo iure maxime minima minus natus obcaecati odio officiis quae quam quas quasi qui ratione repellendus similique vero voluptatem voluptates. Ab at beatae commodi cumque earum eligendi enim exercitationem explicabo facilis incidunt itaque labore laboriosam minima mollitia nemo, nostrum odio possimus quaerat quibusdam quod recusandae reprehenderit, sint tenetur totam ullam vero voluptatem voluptatum. Corporis cumque doloribus ducimus error excepturi placeat repellendus sunt. Accusamus consequatur doloribus dolorum ducimus neque optio vel? Commodi minima molestiae placeat quasi rerum?</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur atque commodi cupiditate delectus dignissimos dolorem enim error est et ex, excepturi harum hic id illo iure maxime minima minus natus obcaecati odio officiis quae quam quas quasi qui ratione repellendus similique vero voluptatem voluptates. Ab at beatae commodi cumque earum eligendi enim exercitationem explicabo facilis incidunt itaque labore laboriosam minima mollitia nemo, nostrum odio possimus quaerat quibusdam quod recusandae reprehenderit, sint tenetur totam ullam vero voluptatem voluptatum. Corporis cumque doloribus ducimus error excepturi placeat repellendus sunt. Accusamus consequatur doloribus dolorum ducimus neque optio vel? Commodi minima molestiae placeat quasi rerum?</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur atque commodi cupiditate delectus dignissimos dolorem enim error est et ex, excepturi harum hic id illo iure maxime minima minus natus obcaecati odio officiis quae quam quas quasi qui ratione repellendus similique vero voluptatem voluptates. Ab at beatae commodi cumque earum eligendi enim exercitationem explicabo facilis incidunt itaque labore laboriosam minima mollitia nemo, nostrum odio possimus quaerat quibusdam quod recusandae reprehenderit, sint tenetur totam ullam vero voluptatem voluptatum. Corporis cumque doloribus ducimus error excepturi placeat repellendus sunt. Accusamus consequatur doloribus dolorum ducimus neque optio vel? Commodi minima molestiae placeat quasi rerum?</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur atque commodi cupiditate delectus dignissimos dolorem enim error est et ex, excepturi harum hic id illo iure maxime minima minus natus obcaecati odio officiis quae quam quas quasi qui ratione repellendus similique vero voluptatem voluptates. Ab at beatae commodi cumque earum eligendi enim exercitationem explicabo facilis incidunt itaque labore laboriosam minima mollitia nemo, nostrum odio possimus quaerat quibusdam quod recusandae reprehenderit, sint tenetur totam ullam vero voluptatem voluptatum. Corporis cumque doloribus ducimus error excepturi placeat repellendus sunt. Accusamus consequatur doloribus dolorum ducimus neque optio vel? Commodi minima molestiae placeat quasi rerum?</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur atque commodi cupiditate delectus dignissimos dolorem enim error est et ex, excepturi harum hic id illo iure maxime minima minus natus obcaecati odio officiis quae quam quas quasi qui ratione repellendus similique vero voluptatem voluptates. Ab at beatae commodi cumque earum eligendi enim exercitationem explicabo facilis incidunt itaque labore laboriosam minima mollitia nemo, nostrum odio possimus quaerat quibusdam quod recusandae reprehenderit, sint tenetur totam ullam vero voluptatem voluptatum. Corporis cumque doloribus ducimus error excepturi placeat repellendus sunt. Accusamus consequatur doloribus dolorum ducimus neque optio vel? Commodi minima molestiae placeat quasi rerum?</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur atque commodi cupiditate delectus dignissimos dolorem enim error est et ex, excepturi harum hic id illo iure maxime minima minus natus obcaecati odio officiis quae quam quas quasi qui ratione repellendus similique vero voluptatem voluptates. Ab at beatae commodi cumque earum eligendi enim exercitationem explicabo facilis incidunt itaque labore laboriosam minima mollitia nemo, nostrum odio possimus quaerat quibusdam quod recusandae reprehenderit, sint tenetur totam ullam vero voluptatem voluptatum. Corporis cumque doloribus ducimus error excepturi placeat repellendus sunt. Accusamus consequatur doloribus dolorum ducimus neque optio vel? Commodi minima molestiae placeat quasi rerum?</p>
        </div>
    )
}

export default HomePage;